"""Generate submission/.env with local-only random credentials.

Mirrors scripts/bootstrap.py: generate once, refuse to overwrite, never commit.
The exercise .gitignore already anticipates submission/.env.

The database is reachable only on a private Compose network and publishes no
port, but it still gets a real random password rather than a default, because
"it is not reachable" is a network claim and passwords are the thing that stays
true when the network claim stops being true.

    python submission/setup_env.py
"""

from __future__ import annotations

import secrets
import sys
from pathlib import Path

ENV = Path(__file__).resolve().parent / ".env"

TEMPLATE = """\
# Generated by setup_env.py. Local-only credentials. Never commit this file.
PIPELINE_DB_PASSWORD={password}

# --- Business semantics (see docs/ASSUMPTIONS.md) -------------------------
# A1: the business day. UTC yields 540 report rows, Asia/Bangkok yields 558.
BUSINESS_TIMEZONE=Asia/Bangkok
# A2: does clearance filter aggregates, or only case detail?
CLEARANCE_FILTERS_AGGREGATES=true

# --- Ingestion tuning -----------------------------------------------------
PAGE_LIMIT=200
POLL_IDLE_SECONDS=3
INTROSPECT_CACHE_SECONDS=5

# --- Deployment shape -----------------------------------------------------
# all | api | worker. Splitting the worker out is configuration, not a rewrite.
ROLE=all
LOG_LEVEL=INFO
"""


def main() -> int:
    if ENV.exists():
        print(f"{ENV} already exists; keep it, or archive it before a fresh setup.", file=sys.stderr)
        return 1
    ENV.write_text(TEMPLATE.format(password=secrets.token_urlsafe(32)), encoding="utf-8")
    print(f"Wrote {ENV} with a random database password. Do not commit it.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
